//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanxetphim
    {
        public int stt { get; set; }
        public string Ten { get; set; }
        public string noidung { get; set; }
        public Nullable<int> maphim { get; set; }
    
        public virtual Phim Phim { get; set; }
    }
}
