//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.Anhs = new HashSet<Anh>();
            this.nhanxetphims = new HashSet<nhanxetphim>();
        }
    
        public int MaPhim { get; set; }
        [Required(ErrorMessage ="Tên phim không được phép null")]
        public string TenPhim { get; set; }
        //[Required(ErrorMessage = "Bạn phải lựa chọn file ảnh")]
        public string TenAnh { get; set; }
        [StringLength(300,ErrorMessage ="Nội dung phải có tối đa 100 kí tự",MinimumLength =5)]
        public string NoiDung { get; set; }
        public string DienVien { get; set; }
        public string LinkPhim { get; set; }
        public string LinkVideo { get; set; }
        public Nullable<int> MaTheLoai { get; set; }
        public Nullable<double> diemphim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anh> Anhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhanxetphim> nhanxetphims { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
