//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiWeb.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text;

    public partial class taikhoan
    {
        public int stt { get; set; }
        [Required(ErrorMessage="Bạn nhập sai tài khoản")]
        public string Tentk { get; set; }
        [Required(ErrorMessage ="Bạn nhập sai mật khẩu")]
        public string matkhau { get; set; }
        public string email { get; set; }
        public void tv()
        {
            Console.OutputEncoding = Encoding.UTF8;
        }
    }
}
